# Generated by Django 3.2 on 2021-06-05 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', 'comments_seed'),
        ('seed', 'votes_seed'),
    ]

    operations = [
    ]
