# Generated by Django 3.1.7 on 2021-06-04 16:30
import logging
from random import choice

from django.db import migrations

from comments.serializer import CommentSerializer
from posts.models import Post
from posts.serializer import PostSerializer
from unions.models import Union
from users.models import User


def create_comments(a, b):
    """Create posts"""
    logging.info("Creating comments")

    description = [
        "My 45 year old daughter rates this icons very radiant mate",
        "Just simple, friend.",
        "I think I'm crying. It's that sublime.",
        "Adore your camera angle :-)",
        "Sleek colour.",
        "This shot blew my mind.",
        "Immensely beastly shot =)",
        "Blur, gradient, job, shot – sublime :-)",
        "Extra incredible!",
        "I want to learn this kind of design! Teach me.",
        "Let me take a nap... great camera angle, anyway.",
        "Nice use of slate grey in this shot.",
        "It's good not just magical!",
        "Engaging, friend. I admire the use of background image and typography!",
        "So fun and amazing dude",
    ]

    for post in Post.objects.all():

        for i in range(8):
            random_user: User = choice(list(User.objects.all()))

            comment = {
                "user_id": random_user.user_id,
                "text": choice(description),
                "post": post.post_id,
            }

            ser = CommentSerializer(data=comment)
            ser.is_valid(raise_exception=True)
            ser.save()
            logging.info(f"{comment} comment created.")


    return True


class Migration(migrations.Migration):
    dependencies = [
        ('seed', 'users_seed'),
        ('seed', 'unions_seed'),
        ('seed', 'posts_seed'),
    ]

    operations = [
        migrations.RunPython(create_comments),
    ]
