# Generated by Django 3.1.7 on 2021-06-04 16:30
import logging
from random import choice

from django.db import migrations

from posts.serializer import PostSerializer
from unions.models import Union
from users.models import User


def create_posts(a, b):
    """Create posts"""
    logging.info("Creating posts")
    titles = ["The Best Kept Secrets About Crypto",
              "The Ugly Truth About Crypto",
              "How to Explain Crypto to a Five-Year-Old",
              "Don't Buy Into These 'Trends' About Crypto",
              "What the Best Crypto Pros Do (and You Should Too)",
              "What I Wish I Knew a Year Ago About Crypto",
              "An Introduction to Crypto",
              "Superstars We'd Love to Recruit for Our Crypto Team",
              "Ways to Completely Sabotage Your Crypto",
              "Why It's Easier to Succeed With Crypto Than You Might Think"
              ]

    description = [
        "Another best tool to create various types of headlines with just one keyword or topic, as this tool by "
        "OnlineSales is helpful for every blogger and content marketing with its potential to create 150 content "
        "ideas in just one click. Yes, all you have to do is type one keyword and hit the generate button to get 150 "
        "content headline ideas without waiting for a second or signing up for an account.",
        "As TweakYourBiz is a business, marketing, and growth tips related blog, and a resource for various "
        "marketers, they are also offering a free of cost headline generator. Yes, TweakYourBiz title generator is "
        "one of the most amazing tools for creating unlimited catchy titles from best, questions, how to, motivation, "
        "business, and various other categories. Use this tool and you will definitely have over 6 months of content "
        "ideas in just minutes.",
        "This tool is not that perfect, as in my experience it was just a random tool created with highly optimized "
        "web-page to gain some traffic for the HookAgency website. However, it is a useful tool for newbies to play "
        "with headline generators and learn how to use them for creating most engaging post titles",
        "If you are looking for a fully-functional most advanced headline generator and a tool that adopts your "
        "website-type and pickup your niche to create custom titles, then The Hoth is here to help you without "
        "charging a penny. Yes, the team behind TheHoth is really amazing that they have created a kickass tool to "
        "create extraordinary and customized content ideas with SEOptimized titles that can catch eyes of Google "
        "users and increase your CTR in no time.",
        "Want to get relief and generate blog post titles for a 3 months publishing calendar? with Kopywriting "
        "Kourse, you can do it in just some seconds. Yes, its possible, as Kopywriting Kourse is giving you access to "
        "their 100 unique titles that can be used for any industry and you can copy+paste them to any file editor, "
        "then print out and make a file where you store your content ideas. This will help you publish blog posts "
        "consistently as you will have 100 blog titles with you.",
        "As long as you are looking for an article title generator. SEOpressor creates outstanding and almost every "
        "type of blog title ideas. This tool is free and can be used to create unlimited blog post titles for every "
        "niche. As they say, it’s the best tool to create headlines that sell and you can create titles with "
        "categories like Generic terms. Product or Brand Name, About An Event, Industry Related, Location Based, "
        "Name Wise or Skill wise.",
        "One of the best and oldest blog title generators I have seen in my blogging career. I’ve used this tool for "
        "some of my content writing services (clients) and they all were happy with the tool. However, "
        "it is not really an impressive tool but helps you create trendy and entertaining headlines. In addition, "
        "increase conversions on your blog and drive good traffic with a low bounce rate.",
        "No doubts that FatJoe is setting industry standards in the SEO world and they are aiming for big wins. They "
        "are also giving back to the community with their 100% free blog post title idea generator. You can put/type "
        "any word (as a topic) in the title generator bar and hit “Generate Blog Title Ideas” button. It will get a "
        "list of top 10 relative and awesome blog post titles. However, you can create 100 more or use the tool again "
        "and again to create unlimited content ideas.",
        "HubSpot is a leading marketing software and with many other services. So, its a leading brand for various "
        "businesses. However, as they are providing a blog ideas generator for free, I can’t complete this article "
        "without mentioning this tool. It’s a great tool. It’s free and has the potential to create engaging "
        "headlines. Moreover, they are putting too much in the tool to get people engaged with the HubSpot brand. "
        "That’s why on the user-experience basis.",
        "Finally, in the case that you don’t want the already used titles. Want to add some of your own words to "
        "every blog post title that is generated via tools. This platform is for you. In addition, ImpactBND is "
        "helping you to select a topic. Then create ideas for that topic with touching and adding your own words in "
        "each and every title that is generated by the tool",
        "Finally, in the case that you don’t want the already used titles. Want to add some of your own words to "
        "every blog post title that is generated via tools. This platform is for you. In addition, ImpactBND is "
        "helping you to select a topic. Then create ideas for that topic with touching and adding your own words in "
        "each and every title that is generated by the tool",
    ]

    for i in range(40):
        random_union = choice(list(Union.objects.all()))
        random_user = choice(list(User.objects.all()))

        post = {
            "title": choice(titles),
            "message": choice(description),
            "union": random_union,
            "user": random_user.user_id
        }

        ser = PostSerializer(data=post)
        ser.is_valid(raise_exception=True)
        ser.save()
        logging.info(f"{post} post created.")

    return True


class Migration(migrations.Migration):
    dependencies = [
        ('seed', 'unions_seed'),
        ('posts', '0003_post_user'),
        ('seed', 'users_seed'),
    ]

    operations = [
        migrations.RunPython(create_posts),
    ]
