# Generated by Django 3.1.7 on 2021-06-04 16:30
import logging

from django.db import migrations

from users.models import User


def create_users(a, b):
    """Create users"""
    logging.info("Creating users")
    # sha256 hash of 'testpass'
    encryptedPassword = '13d249f2cb4127b40cfa757866850278793f814ded3c587fe5889e889a7a9f6c'

    for i in range(15):
        email = "user%s@gmail.com".replace("%s", str(i))
        username = "user" + str(i)
        user = User.objects.create_user(username=username, email=email, password=encryptedPassword)
        user.save()
        logging.info(f"{user} user created.")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_users),
    ]
