# Generated by Django 3.1.7 on 2021-03-16 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('union', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('message', models.TextField()),
                ('upvotes', models.IntegerField()),
                ('downvotes', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('union_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='union.union')),
            ],
        ),
    ]
