# Generated by Django 3.1.7 on 2021-04-19 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
        ('unions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='union_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unions.union'),
        ),
    ]
