# Generated by Django 3.1.7 on 2021-04-19 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='union_id',
            new_name='union',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
    ]
