# Generated by Django 3.2.4 on 2021-06-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.TextField(choices=[('UPVOTE', 'Upvote'), ('NEUTRAL', 'Neutral'), ('DOWNVOTE', 'Downvote')]),
        ),
    ]
