# Generated by Django 3.1.7 on 2021-05-03 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='invite_acceptor_id',
            new_name='invite_acceptor',
        ),
        migrations.RenameField(
            model_name='invitation',
            old_name='invite_creator_id',
            new_name='invite_creator',
        ),
    ]
