# Generated by Django 3.1.7 on 2021-05-03 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invitations', '0002_auto_20210503_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='union_id',
            new_name='union',
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invite_acceptor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invite_acceptor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invite_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invite_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
