# Generated by Django 3.1.7 on 2021-05-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_auto_20210503_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
