# Generated by Django 3.1.7 on 2021-06-04 16:30
import logging
from random import choice

from django.db import migrations

from posts.serializer import PostSerializer
from unions.models import Union
from users.models import User


def create_posts(a, b):
    """Create posts"""
    logging.info("Creating posts")

    for i in range(40):
        random_union = choice(list(Union.objects.all()))
        random_user = choice(list(User.objects.all()))

        post = {
            "title": "What is this?",
            "message": "This is the description",
            "union": random_union,
            "user": random_user.user_id
        }

        ser = PostSerializer(data=post)
        ser.is_valid(raise_exception=True)
        ser.save()
        logging.info(f"{post} post created.")

    return True


class Migration(migrations.Migration):
    dependencies = [
        ('unions', 'unions_seed'),
        ('posts', '0003_post_user'),
        ('users', 'users_seed'),
    ]

    operations = [
        migrations.RunPython(create_posts),
    ]
