# Generated by Django 3.1.7 on 2021-05-19 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Union',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('members_can_invite', models.BooleanField()),
                ('icon', models.TextField(null=True)),
                ('banner', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnionUsers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invites_left', models.IntegerField(default=2)),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unions.union')),
            ],
        ),
    ]
