# Generated by Django 3.1.7 on 2021-03-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='union',
            old_name='avatar',
            new_name='icon',
        ),
        migrations.AddField(
            model_name='union',
            name='banner',
            field=models.TextField(default='NULL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='union',
            name='members_can_invite',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
