# Generated by Django 3.1.7 on 2021-03-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unions', '0002_auto_20210324_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='union',
            name='banner',
            field=models.TextField(null=True),
        ),
    ]
