# Generated by Django 3.2.3 on 2021-05-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unions', '0002_auto_20210519_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='union',
            name='banner',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='union',
            name='icon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
