# Generated by Django 3.1.7 on 2021-05-19 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unions', '0003_auto_20210517_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='union',
            name='union_users',
        ),
        migrations.AlterField(
            model_name='union',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='UnionUsers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invites_left', models.IntegerField(default=2)),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unions.union')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='union',
            name='users',
            field=models.ManyToManyField(related_name='users', through='unions.UnionUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
