# Generated by Django 3.1.7 on 2021-03-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unions', '0003_auto_20210324_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='union',
            name='icon',
            field=models.TextField(null=True),
        ),
    ]
