# Generated by Django 3.1.7 on 2021-05-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unions', '0003_auto_20210517_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='union',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
