# Generated by Django 3.1.7 on 2021-05-19 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unions', '0004_auto_20210519_1349'),
        ('unions', '0003_auto_20210518_1000'),
    ]

    operations = [
    ]
