# Generated by Django 3.1.7 on 2021-04-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('union', '0002_auto_20210412_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='union',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
