# Generated by Django 3.1.7 on 2021-04-21 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='children',
        ),
    ]
