# Generated by Django 3.1.7 on 2021-04-14 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20210414_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comments.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='child_ids',
            field=models.ManyToManyField(blank=True, default=[], related_name='_comment_child_ids_+', to='comments.Comment'),
        ),
    ]
