# Generated by Django 3.1.7 on 2021-04-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20210414_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='child_ids',
        ),
        migrations.AddField(
            model_name='comment',
            name='children',
            field=models.ManyToManyField(blank=True, default=[], related_name='_comment_children_+', to='comments.Comment'),
        ),
    ]
