# Generated by Django 3.2.3 on 2021-06-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnionImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('union_id', models.IntegerField()),
                ('banner', models.TextField()),
                ('icon', models.TextField()),
            ],
        ),
    ]
