# Generated by Django 3.2.3 on 2021-06-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unionImages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unionimages',
            name='id',
        ),
        migrations.AlterField(
            model_name='unionimages',
            name='union_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
